### ISSUE TITLE
Effects Panel not appearing

### ISSUE THREAD

**Issue by ckdragons** [DFreds/dfreds-effects-panel#33]
I'm sure I'm doing something wrong here. I installed this module, set the permissions on both fields to Player though I'm the GM. Selected one of the tokens on the canvas and nothing.

To start, I'm using PF1e. Is this a 5e-only module?

**Comment by MotoMoto1234** [comment]
I am pretty sure that this is the byproduct of a typo in the module.json.  Dfred, I think you left in the system version field even though theres no system defined, so its adversely effecting non dnd system users since pathfinders got a low version number vs what you left in:

![image](https://user-images.githubusercontent.com/116308065/213835726-992525be-aa32-4096-9f5c-a6ae6d8214dc.png)

**Comment by DFreds** [comment]
Nah, this is because of something else. Should be fixed in v2.0.4 though. Thanks for the report!
